version: '3'

services:
  scylladb-01:
    image: scylladb/scylla:5.2.2
    networks:
      andean_net:
        ipv4_address: 172.19.0.4
    healthcheck:
      test: ["CMD-SHELL", "sh -c $(curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport')"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: scylladb-01
    hostname: scylladb-01
    command: "--seeds 172.19.0.4 --cpuset 0 --memory 256M --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE
  scylladb-02:
    image: scylladb/scylla:5.2.2
    networks:
      andean_net:
        ipv4_address: 172.19.0.5
    container_name: scylladb-02
    hostname: scylladb-02
    command: "--seeds 172.19.0.4 --cpuset 1 --memory 256M --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD-SHELL", "sh -c $(curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport')"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      scylladb-01:
        condition: service_healthy

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - andean_net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - andean_net

  andean_pipeline:
    build: .
    networks:
      andean_net:
        ipv4_address: 172.19.0.10    
    container_name: andean_pipeline
    hostname: andean_pipeline
    volumes:
      - ./:/usr/src/andean_pipeline
    tty: true

  andean_producer:
    build:
      context: ./producer
    networks:
      andean_net:
        ipv4_address: 172.19.0.11
    container_name: andean_producer
    hostname: andean_producer
    volumes:
      - ./producer:/usr/src/andean_producer
    tty: true

networks:
  andean_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1
